{% set name = "git-delta" %}
{% set version = "0.18.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/dandavison/delta/archive/refs/tags/{{ version }}.tar.gz
  sha256: ef558e0ee4c9a10046f2f8e2e59cf1bedbb18c2871306b772d3d9b8e3b242b9c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - cargo-bundle-licenses
  host:
    - zlib

test:
  commands:
    - delta --version

about:
  home: https://github.com/dandavison/delta
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: A syntax-highlighting pager for git, diff, and grep output.

extra:
  recipe-maintainers:
    - YYYasin19
    - pavelzw
