schema_version: 1

context:
  version: "0.19.2"

package:
  name: git-delta
  version: ${{ version }}

source:
  url: https://github.com/dandavison/delta/archive/refs/tags/${{ version }}.tar.gz
  sha256: f59b86f8c8dda4d76a3ba34b8553777a20c3b461646917d8e480fac6531bba9f
  patches:
    - 0001-fallback-to-temporary-cache-directory.patch

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - zlib

tests:
  - files:
      recipe:
        - test.diff
    script:
      - delta --version
      - delta --no-gitconfig --paging=never < test.diff > delta.out
      - if: win
        then:
          - findstr /C:"from delta" delta.out
          - if errorlevel 1 exit 1
      - if: unix
        then: grep -F "from delta" delta.out

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: A syntax-highlighting pager for git, diff, and grep output.
  homepage: https://github.com/dandavison/delta

extra:
  recipe-maintainers:
    - YYYasin19
    - pavelzw
