schema_version: 1

context:
  name: git-delta
  version: "0.19.1"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://github.com/dandavison/delta/archive/refs/tags/${{ version }}.tar.gz
  sha256: a2089af1b86264d45a2b5872708701aca4506d1c092be23017bb610af369f283

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - zlib

tests:
  - script:
      - delta --version

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: A syntax-highlighting pager for git, diff, and grep output.
  homepage: https://github.com/dandavison/delta

extra:
  recipe-maintainers:
    - YYYasin19
    - pavelzw
